server:
  port: 8070
  servlet:
    context-path: /mirror

spring:
  jpa:
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/mirror
    username: mirror_adm
    password: ${POSTGRES_PASSWORD:root}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml




